language: android
jdk: oraclejdk7
env:
  global:
  - ANDROID TOOLS_API=24
  - ANDROID_BUILD_TOOLS=24.0.2
android:
components:
- patform-tools
- tools
before_install:
- mkdir "$ANDROID_HOME/licenses || true"
#- echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
#- echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
- chmod -x gradlew
- "./gradlew dependencies || true"
before_script:
- echo no | android create avd --force -n test -t android-21 --abi armeabi-v7a
- emulator -avd test -no-skin -no-audio -no-window &
- android-wait-for-emulator
- adb shell input keyevent 82 &
script:
- "./gradlew clean build connectedAndroidTest -PdisablePreDex --stacktrace"
